services:
  app:
    build: .
    container_name: home-recipe-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db-3fpgfk.vpc-cdb.ntruss.com:3306/app?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: choi
      JAVA_OPTS: "-Xms256m -Xmx512m"
    restart: unless-stopped
